// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Johan Sebastian Giraldo Hurtado"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Valida credenciales y devuelve un JWT válido por 24 horas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Autenticar usuario",
                "parameters": [
                    {
                        "description": "Correo y contraseña",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/grades": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea o actualiza (upsert) la nota de una actividad para una matrícula.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Registrar o actualizar una nota",
                "parameters": [
                    {
                        "description": "Datos de la nota (valor entre 0 y 5)",
                        "name": "grade",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.RecordGradeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Grade"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/grades/{id}/comment": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Actualizar el comentario de una nota",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la nota (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevo comentario",
                        "name": "comment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.UpdateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Healthcheck del servicio",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.MessageResponse"
                        }
                    }
                }
            }
        },
        "/sessions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea una sesión y genera automáticamente los espacios (slots) según la duración.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Crear sesión de clase con sus espacios",
                "parameters": [
                    {
                        "description": "Datos de la sesión",
                        "name": "session",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.CreateSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/active": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Obtener la sesión activa de una materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "subject_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Session"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/activate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Iniciar una sesión de clase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la sesión (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/deactivate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Finalizar una sesión de clase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la sesión (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/slots": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Listar los espacios (slots) de una sesión",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la sesión (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Slot"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sessions/{id}/slots/{slotID}/reserve": {
            "post": {
                "description": "Reserva un turno para un estudiante. Devuelve 409 si el espacio ya está tomado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "slots"
                ],
                "summary": "Reservar un espacio de una sesión",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la sesión (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID del espacio (UUID)",
                        "name": "slotID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ID del estudiante",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ReserveSlotRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Slot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/students": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Crear estudiante",
                "parameters": [
                    {
                        "description": "Datos del estudiante",
                        "name": "student",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.RegisterStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Student"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/students/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "students"
                ],
                "summary": "Actualizar estudiante",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del estudiante (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del estudiante",
                        "name": "student",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.UpdateStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Student"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "Listar materias del docente autenticado",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Subject"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "Crear materia",
                "parameters": [
                    {
                        "description": "Datos de la materia",
                        "name": "subject",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.CreateSubjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Subject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "Eliminar materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "Actualizar materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de la materia",
                        "name": "subject",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.UpdateSubjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Subject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects/{id}/enroll": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "Matricular estudiante en una materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ID del estudiante",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.enrollStudentBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Enrollment"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects/{id}/final-grades": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Obtener las notas definitivas de una materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.FinalGrade"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects/{id}/grades": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve cortes, estudiantes, matrículas, notas y notas definitivas calculadas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Obtener la planilla completa de notas de una materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_service.SubjectGradesResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects/{id}/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Importa estudiantes, estructura de evaluación y notas en una sola operación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "Importar datos masivos de una materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a importar",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ImportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ImportResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subjects/{id}/students": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subjects"
                ],
                "summary": "Listar estudiantes de una materia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la materia (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Student"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_johansgiraldo_noteops_backend_internal_models.Activity": {
            "type": "object",
            "properties": {
                "cut_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "scheduled_at": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.CreateSessionRequest": {
            "type": "object",
            "required": [
                "duration_min",
                "slot_min",
                "starts_at",
                "subject_id"
            ],
            "properties": {
                "duration_min": {
                    "type": "integer",
                    "minimum": 5
                },
                "room": {
                    "type": "string"
                },
                "slot_min": {
                    "type": "integer",
                    "minimum": 5
                },
                "starts_at": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.CreateSessionResponse": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Session"
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Slot"
                    }
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.CreateSubjectRequest": {
            "type": "object",
            "required": [
                "name",
                "period"
            ],
            "properties": {
                "faculty": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.Cut": {
            "type": "object",
            "properties": {
                "activities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Activity"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "subject_id": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.Enrollment": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Mensaje de error legible"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.FinalGrade": {
            "type": "object",
            "properties": {
                "enrollment_id": {
                    "type": "string"
                },
                "final_grade": {
                    "type": "number"
                },
                "student_id": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.Grade": {
            "type": "object",
            "properties": {
                "activity_id": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "enrollment_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recorded_at": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.ImportGradeRow": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string"
                },
                "cut_number": {
                    "type": "integer"
                },
                "student_code": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.ImportRequest": {
            "type": "object",
            "properties": {
                "grades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ImportGradeRow"
                    }
                },
                "structure": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ImportStructureRow"
                    }
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.ImportStudentRow"
                    }
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.ImportResult": {
            "type": "object",
            "properties": {
                "activities_created": {
                    "type": "integer"
                },
                "cuts_created": {
                    "type": "integer"
                },
                "grades_imported": {
                    "type": "integer"
                },
                "students_created": {
                    "type": "integer"
                },
                "students_enrolled": {
                    "type": "integer"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.ImportStructureRow": {
            "type": "object",
            "properties": {
                "activity_name": {
                    "type": "string"
                },
                "activity_weight": {
                    "type": "number"
                },
                "cut_name": {
                    "type": "string"
                },
                "cut_number": {
                    "type": "integer"
                },
                "cut_weight": {
                    "type": "number"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.ImportStudentRow": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.User"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operación realizada"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.RecordGradeRequest": {
            "type": "object",
            "required": [
                "activity_id",
                "enrollment_id",
                "value"
            ],
            "properties": {
                "activity_id": {
                    "type": "string"
                },
                "comment": {
                    "type": "string"
                },
                "enrollment_id": {
                    "type": "string"
                },
                "value": {
                    "type": "number",
                    "maximum": 5,
                    "minimum": 0
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.RegisterStudentRequest": {
            "type": "object",
            "required": [
                "email",
                "full_name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.ReserveSlotRequest": {
            "type": "object",
            "required": [
                "student_id"
            ],
            "properties": {
                "student_id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.Session": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "duration_min": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                },
                "slot_min": {
                    "type": "integer"
                },
                "starts_at": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.Slot": {
            "type": "object",
            "properties": {
                "duration_min": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "reserved_at": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "starts_at": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.Student": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.Subject": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "faculty": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                },
                "teacher_id": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.UpdateCommentRequest": {
            "type": "object",
            "required": [
                "comment"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.UpdateStudentRequest": {
            "type": "object",
            "required": [
                "email",
                "full_name"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.UpdateSubjectRequest": {
            "type": "object",
            "required": [
                "name",
                "period"
            ],
            "properties": {
                "faculty": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "description": "teacher | admin",
                    "type": "string"
                }
            }
        },
        "github_com_johansgiraldo_noteops_backend_internal_service.SubjectGradesResult": {
            "type": "object",
            "properties": {
                "cuts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Cut"
                    }
                },
                "enrollments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Enrollment"
                    }
                },
                "final_grades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.FinalGrade"
                    }
                },
                "grades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Grade"
                    }
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_johansgiraldo_noteops_backend_internal_models.Student"
                    }
                }
            }
        },
        "internal_handlers.enrollStudentBody": {
            "type": "object",
            "required": [
                "student_id"
            ],
            "properties": {
                "student_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Escribe **Bearer \u0026lt;token\u0026gt;** usando el JWT obtenido en /api/auth/login.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "NoteOPs API",
	Description:      "API REST de gestión de notas académicas con cálculo automático de nota definitiva, sesiones de clase en tiempo real y reserva de turnos.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
